pipeline {
    agent any
    environment {
        IMAGE_NAME = 'anas587/kubernets-app-app'
        DEPLOYMENT_FILE = 'deployment.yaml'
        WORK_DIR = 'jenkins-ci-cd/lab-25/Jenkins_App'
        DEPLOYMENT_DIR = 'jenkins-ci-cd/lab-25/gitops'
        GIT_CREDENTIALS_ID = 'GitHub'  
        ARGOCD_REPO = 'https://github.com/Anas990978/Ivolve_Training.git'
        ARGOCD_BRANCH = 'main'
    }
    stages {
        stage('run unit tests') {
            steps {
                sh 'echo "Running unit tests..."'
                dir("${WORK_DIR}") {
                    sh 'mvn test'
                }
            }
        }
        stage('Build') {
            steps {
                dir("${WORK_DIR}") {
                    sh 'mvn package'
                }
            }
        }
        
        stage('Docker Build') {
            steps {
                dir("${WORK_DIR}") {
                    sh 'docker build -t $IMAGE_NAME:$BUILD_NUMBER .'
                }
            }
        }
        stage('Docker Push') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    withCredentials([usernamePassword(credentialsId: 'DockerHub', usernameVariable: 'DOCKERHUB_USERNAME', passwordVariable: 'DOCKERHUB_PASSWORD')]) {
                        sh '''
                            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
                            docker push $IMAGE_NAME:$BUILD_NUMBER
                        '''
                    }
                }
            }
        }        
        stage('delete image from local') {
            steps {
                sh 'docker rmi $IMAGE_NAME:$BUILD_NUMBER || true'
            }
        }
        
        stage('Clone ArgoCD YAML Repo') {
            steps {
               
                sh 'rm -rf argocd-repo'
                dir('argocd-repo') {
                    git branch: "${ARGOCD_BRANCH}",
                        credentialsId: "${GIT_CREDENTIALS_ID}",
                        url: "${ARGOCD_REPO}"
                }
            }
        }
        
        stage('Update Deployment File and Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: GIT_CREDENTIALS_ID, usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    dir("argocd-repo/${DEPLOYMENT_DIR}") {
                        sh """
                            git config user.email "jenkins@ci.com"
                            git config user.name "Jenkins"
                            sed -i 's|image: .*|image: ${IMAGE_NAME}:${BUILD_NUMBER}|' ${DEPLOYMENT_FILE}
                            git add ${DEPLOYMENT_FILE}
                            git commit -m "Update deployment image to ${IMAGE_NAME}:${BUILD_NUMBER} by Jenkins" || echo "No changes to commit"
                            git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Anas990978/Ivolve_Training.git ${ARGOCD_BRANCH}
                        """
                    }
                }
            }
        }
        
        
        /*
        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([
                    string(credentialsId: 'ServiceAccount-Token', variable: 'TOKEN'),
                    string(credentialsId: 'API Server', variable: 'API_SERVER')
                ]) {
                    dir("${DEPLOYMENT_DIR}") {
                        sh 'kubectl apply -f $DEPLOYMENT_FILE -n ivolve --server=$API_SERVER --token=$TOKEN --insecure-skip-tls-verify=true --validate=false'
                    }
                }
            }
        }
        */
    }
    post {
        always {
            echo 'Pipeline execution completed'
            sh 'docker logout || true'
            sh 'rm -rf argocd-repo || true'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline execution failed!'
        }
    }
}