@Library('shared-lib') _

pipeline {
    agent { label 'agent-1' }
    environment {
        IMAGE_NAME = 'anas587/kubernets-app-app'
        DEPLOYMENT_FILE = 'deployment.yaml'
        DockerHub_Credentials_ID ='DockerHub'
        Token_Credentials_ID = 'ServiceAccount-Token'
        APIServer_Credentials_ID = 'API Server'
        SonarQube_Token_ID = 'SONAR_TOKEN'
        WORK_DIR = 'jenkins-ci-cd/lab-23/Jenkins_App'
    }
    stages {
        stage('Build and Test') {
            steps {
                dir("${WORK_DIR}") {
                    buildApp()
                }
            }
        }
        stage('SonarQube Analysis') {
            steps {
                dir("${WORK_DIR}") {
                    sonarQubeAnalysis(SonarQube_Token_ID)
                }
            }
        }
        
        stage('Docker Build and Push') {
            steps {
                dir("${WORK_DIR}") {
                    buildAndpushImage(IMAGE_NAME, DockerHub_Credentials_ID)
                }
            }
        }
        stage('Image Security Scan') {
             steps {
                 dir("${WORK_DIR}") {
                     scanDockerImage(IMAGE_NAME)
                 }
             }
        }

        stage('Deploy to Kubernetes') {
            steps {
                 
                    deployToK8s(IMAGE_NAME, DEPLOYMENT_FILE, APIServer_Credentials_ID, Token_Credentials_ID)
                
            }
        }
    }
    post {
        always {
            echo 'Pipeline execution completed'
            sh 'docker logout || true'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline execution failed!'
        }
    }
}
