@Library('shared-lib') _

pipeline {
    agent any
    environment {
        IMAGE_NAME = 'anas587/kubernets-app-app'
        DEPLOYMENT_FILE = 'deployment.yaml'
        DockerHub_Credentials_ID ='DockerHub'
        Token_Credentials_ID = 'ServiceAccount-Token'
        APIServer_Credentials_ID = 'API Server'
        SonarQube_Token_ID = 'SONAR_TOKEN'
    }
    stages {
        stage('Build and Test') {
            steps {
                buildApp()
            }
        }
        stage('SonarQube Analysis') {
            steps {
                sonarQubeAnalysis(SonarQube_Token_ID)
            }
        }
        
        stage('Docker Build and Push') {
            steps {
                buildAndpushImage(IMAGE_NAME, DockerHub_Credentials_ID)
            }
        }
        stage('Image Security Scan') {
             steps {
                 scanDockerImage(IMAGE_NAME)
             }
        }

        stage('Deploy to Kubernetes') {
            steps {
                deployToK8s(IMAGE_NAME, DEPLOYMENT_FILE, APIServer_Credentials_ID, Token_Credentials_ID)
            }
        }
    }
    post {
        always {
            echo 'Pipeline execution completed'
            sh 'docker logout || true'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline execution failed!'
        }
    }
}